display_name: Clash For Flutter
publisher_display_name: mapleafgo
identity_name: cn.mapleafgo.clash-for-flutter
msix_version: 1.0.0.1
protocol_activation: clash
publisher: CN=B3039CF4-E394-42B6-971C-4BE97F322DE8