appId: cn.mapleafgo.clash_for_flutter
# relative path to the application's icon
icon: assets/icon.png

script:

include: [libgdk-pixbuf2.0-0,libgtk-3-0]
exclude: []
# its true by default
default_excludes: false

files:
  include: []
  exclude: []
  # its true by default
  default_excludes: true
