appId: cn.mapleafgo.clash_for_flutter
# relative path to the application's icon
icon: assets/icon.png

script:

include: [gdk-pixbuf2]
exclude: []
# its true by default
default_excludes: true

files:
  include: []
  exclude: []
  # its true by default
  default_excludes: true
